#define VIAL_KEYBOARD_UID {0xB1, 0x6B, 0x3A, 0xE3, 0x28, 0x64, 0xC1, 0x05}

#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 3}

#define STM32_ONBOARD_EEPROM_SIZE 4098
#define DYNAMIC_KEYMAP_LAYER_COUNT 12

#define COMBO_MUST_PRESS_IN_ORDER
#define VIAL_COMBO_ENTRIES 12
/*#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE 1280 */

/* Worm-circle color config in VIA custom EEPROM */
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 7

/* Idle sleep: 30 minutes */
#define OLED_TIMEOUT 1800000
#define RGB_MATRIX_TIMEOUT 1800000

